# Generated by Django 6.0.3 on 2026-03-18 23:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Examples: "Starters", "Main Courses", "Drinks", "Desserts"', max_length=100, unique=True)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ingredients', models.TextField(help_text='Comma-separated list of ingredients')),
                ('has_allergens', models.BooleanField(default=False, help_text='Check if the dish contains allergenic substances')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the dish is currently on the menu')),
                ('is_available', models.BooleanField(default=True, help_text="If disabled, the dish will appear as 'sold out' and won't be orderable")),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='menu.category')),
            ],
            options={
                'db_table': 'dishes',
            },
        ),
    ]
